# Generated by Django 3.0.5 on 2020-05-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200501_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='chead2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head2',
        ),
    ]
