# Generated by Django 3.0.5 on 2020-04-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Order_id',
            new_name='order_id',
        ),
    ]
